#!/usr/bin/bash

gnome-terminal --tab -- bash -c 'cd ./api; npx kill-port 6789; npx nodemon listen.js; bash'
gnome-terminal --tab -- bash -c 'cd ./client; npx kill-port 5173; npx vite --open; bash'

clear
