name: Api tests / Jest

on:
  push:
    paths:
      - 'api/**'

defaults:
  run:
    working-directory: api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: 'abcde12345'
