name: client tests

on:
  push:
    working-directory:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install modules
        run: |
          npm --prefix api install
          npm --prefix client install

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          working-directory: client
          browser: chrome
          start: |
            npm --prefix ../api listen
            npm  start
          wait-on: 'http://localhost:5173'
        env:
          JWT_SECRET: 'abcde12345'
