name: client tests

on:
  push:
    working-directory:
      - 'client/**'

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install modules
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./client
          browser: chrome
          start: npx vite --host
          wait-on: 'http://localhost:5173'
        env:
          JWT_SECRET: 'abcde12345'
