name: client tests

on:
  push:
    working-directory:
      - 'client/**'

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install modules
        run: npm install

      - name: Start client app
        run: npx vite --host

      - name: Run tests
        run: npm test
